image: node:latest

before_script:
    - npm install

cache:
    paths:
    - node_modules/

publish:
    stage: deploy
    only:
        - tags
    environment:
        name: production
    script:
        - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
        - npm publish
